{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ======================================================================\n",
    "# There are 5 questions in this exam with increasing difficulty from 1-5.\n",
    "# Please note that the weight of the grade for the question is relative\n",
    "# to its difficulty. So your Category 1 question will score significantly\n",
    "# less than your Category 5 question.\n",
    "#\n",
    "# Don't use lambda layers in your model.\n",
    "# You do not need them to solve the question.\n",
    "# Lambda layers are not supported by the grading infrastructure.\n",
    "#\n",
    "# You must use the Submit and Test button to submit your model\n",
    "# at least once in this category before you finally submit your exam,\n",
    "# otherwise you will score zero for this category.\n",
    "# ======================================================================\n",
    "#\n",
    "# NLP QUESTION\n",
    "#\n",
    "# Build and train a classifier for the sarcasm dataset.\n",
    "# The classifier should have a final layer with 1 neuron activated by sigmoid as shown.\n",
    "# It will be tested against a number of sentences that the network hasn't previously seen\n",
    "# and you will be scored on whether sarcasm was correctly detected in those sentences."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Could not find a version that satisfies the requirement json (from versions: none)\n",
      "ERROR: No matching distribution found for json\n",
      "\n",
      "[notice] A new release of pip available: 22.3.1 -> 23.3.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting tensorflow\n",
      "  Using cached tensorflow-2.14.0-cp311-cp311-win_amd64.whl (2.1 kB)\n",
      "Collecting tensorflow-intel==2.14.0\n",
      "  Using cached tensorflow_intel-2.14.0-cp311-cp311-win_amd64.whl (284.2 MB)\n",
      "Requirement already satisfied: absl-py>=1.0.0 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (2.0.0)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (1.6.3)\n",
      "Requirement already satisfied: flatbuffers>=23.5.26 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (23.5.26)\n",
      "Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (0.5.4)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (0.2.0)\n",
      "Requirement already satisfied: h5py>=2.9.0 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (3.10.0)\n",
      "Requirement already satisfied: libclang>=13.0.0 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (16.0.6)\n",
      "Requirement already satisfied: ml-dtypes==0.2.0 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (0.2.0)\n",
      "Requirement already satisfied: numpy>=1.23.5 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (1.26.1)\n",
      "Requirement already satisfied: opt-einsum>=2.3.2 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (3.3.0)\n",
      "Requirement already satisfied: packaging in c:\\users\\samapant\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (23.2)\n",
      "Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (4.25.0)\n",
      "Requirement already satisfied: setuptools in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (65.5.0)\n",
      "Requirement already satisfied: six>=1.12.0 in c:\\users\\samapant\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (1.16.0)\n",
      "Requirement already satisfied: termcolor>=1.1.0 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (2.3.0)\n",
      "Requirement already satisfied: typing-extensions>=3.6.6 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (4.8.0)\n",
      "Requirement already satisfied: wrapt<1.15,>=1.11.0 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (1.14.1)\n",
      "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (0.31.0)\n",
      "Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (1.59.2)\n",
      "Requirement already satisfied: tensorboard<2.15,>=2.14 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (2.14.1)\n",
      "Requirement already satisfied: tensorflow-estimator<2.15,>=2.14.0 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (2.14.0)\n",
      "Requirement already satisfied: keras<2.15,>=2.14.0 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorflow-intel==2.14.0->tensorflow) (2.14.0)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.14.0->tensorflow) (0.41.3)\n",
      "Requirement already satisfied: google-auth<3,>=1.6.3 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (2.23.4)\n",
      "Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (1.0.0)\n",
      "Requirement already satisfied: markdown>=2.6.8 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (3.5.1)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (2.31.0)\n",
      "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (0.7.2)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (3.0.1)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (5.3.2)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (0.3.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (4.9)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (1.3.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (3.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (2.0.7)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (2023.7.22)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from werkzeug>=1.0.1->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (2.1.3)\n",
      "Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (0.5.0)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (3.2.2)\n",
      "Installing collected packages: tensorflow-intel, tensorflow\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\\\Users\\\\samapant\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python311\\\\Lib\\\\site-packages\\\\tensorflow\\\\python\\\\keras\\\\optimizer_v2\\\\adagrad.py'\n",
      "Consider using the `--user` option or check the permissions.\n",
      "\n",
      "\n",
      "[notice] A new release of pip available: 22.3.1 -> 23.3.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: numpy in c:\\users\\samapant\\appdata\\local\\programs\\python\\python311\\lib\\site-packages (1.26.1)Note: you may need to restart the kernel to use updated packages.\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip available: 22.3.1 -> 23.3.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Could not find a version that satisfies the requirement urllib (from versions: none)\n",
      "ERROR: No matching distribution found for urllib\n",
      "\n",
      "[notice] A new release of pip available: 22.3.1 -> 23.3.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "%pip install json\n",
    "%pip install tensorflow\n",
    "%pip install numpy\n",
    "%pip install urllib"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "import tensorflow as tf\n",
    "import numpy as np\n",
    "import urllib\n",
    "from tensorflow.keras.preprocessing.text import Tokenizer\n",
    "from tensorflow.keras.preprocessing.sequence import pad_sequences\n",
    "\n",
    "\n",
    "def solution_model():\n",
    "    url = 'https://storage.googleapis.com/download.tensorflow.org/data/sarcasm.json'\n",
    "    urllib.request.urlretrieve(url, 'sarcasm.json')\n",
    "\n",
    "    # Load the JSON file\n",
    "    with open(\"./sarcasm.json\", 'r') as f:\n",
    "        datastore = json.load(f)\n",
    "\n",
    "# Collect sentences and labels into the lists\n",
    "    # DO NOT CHANGE THIS CODE OR THE TESTS MAY NOT WORK\n",
    "    vocab_size = 1000\n",
    "    embedding_dim = 16\n",
    "    max_length = 120\n",
    "    trunc_type='post'\n",
    "    padding_type='post'\n",
    "    oov_tok = \"<OOV>\"\n",
    "    training_size = 20000\n",
    "\n",
    "    sentences = []\n",
    "    labels = []\n",
    "    # YOUR CODE HERE\n",
    "    for item in datastore:\n",
    "      sentences.append(item['headline'])\n",
    "      labels.append(item['is_sarcastic'])\n",
    "\n",
    "    # Split the sentences\n",
    "    training_sentences = sentences[:training_size]\n",
    "    testing_sentences = sentences[training_size:]\n",
    "\n",
    "    # Split the labels\n",
    "    training_labels = labels[:training_size]\n",
    "    testing_labels = labels[training_size:]\n",
    "\n",
    "    # Initialize the Tokenizer class\n",
    "    tokenizer = Tokenizer(num_words=vocab_size, oov_token=oov_tok)\n",
    "\n",
    "    # Generate the word index dictionary\n",
    "    tokenizer.fit_on_texts(training_sentences)\n",
    "    word_index = tokenizer.word_index\n",
    "\n",
    "    # Generate and pad the training sequences\n",
    "    training_sequences = tokenizer.texts_to_sequences(training_sentences)\n",
    "    training_padded = pad_sequences(training_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)\n",
    "\n",
    "    # Generate and pad the testing sequences\n",
    "    testing_sequences = tokenizer.texts_to_sequences(testing_sentences)\n",
    "    testing_padded = pad_sequences(testing_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)\n",
    "\n",
    "    # Convert the labels lists into numpy arrays\n",
    "    training_labels = np.array(training_labels)\n",
    "    testing_labels = np.array(testing_labels)\n",
    "\n",
    "    lstm_dim = 32\n",
    "    dense_dim = 24\n",
    "\n",
    "    model = tf.keras.Sequential([\n",
    "        # YOUR CODE HERE. KEEP THIS OUTPUT LAYER INTACT OR TESTS MAY FAIL\n",
    "        tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length=max_length),\n",
    "        tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(lstm_dim)),\n",
    "        tf.keras.layers.Dense(dense_dim, activation='relu'),\n",
    "        tf.keras.layers.Dense(1, activation='sigmoid')\n",
    "    ])\n",
    "\n",
    "    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])\n",
    "\n",
    "    # Accuracy 95%\n",
    "    class myCallback(tf.keras.callbacks.Callback):\n",
    "        def on_epoch_end(self, epoch, logs={}):\n",
    "            if logs.get('accuracy') is not None and logs.get('accuracy') > 0.95:\n",
    "                print(\"\\nReached 99.5% accuracy so cancelling training!\")\n",
    "                self.model.stop_training = True\n",
    "    callbacks = myCallback()\n",
    "\n",
    "    # Checkpoint\n",
    "    checkpoint = tf.keras.callbacks.ModelCheckpoint(\n",
    "        filepath=\"Question_4.h5\",\n",
    "        save_weights_only=True,\n",
    "        monitor='val_accuracy',\n",
    "        mode='max',\n",
    "        save_best_only=True,\n",
    "        verbose=1\n",
    "        )\n",
    "\n",
    "    model.fit(training_padded, training_labels,\n",
    "              validation_data=(testing_padded, testing_labels),\n",
    "              epochs=500,\n",
    "              callbacks=[callbacks, checkpoint])\n",
    "\n",
    "    return model "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.4547 - accuracy: 0.7713\n",
      "Epoch 1: val_accuracy improved from -inf to 0.81860, saving model to Question_4.h5\n",
      "625/625 [==============================] - 38s 55ms/step - loss: 0.4547 - accuracy: 0.7713 - val_loss: 0.3911 - val_accuracy: 0.8186\n",
      "Epoch 2/500\n",
      "624/625 [============================>.] - ETA: 0s - loss: 0.3483 - accuracy: 0.8399\n",
      "Epoch 2: val_accuracy did not improve from 0.81860\n",
      "625/625 [==============================] - 46s 73ms/step - loss: 0.3483 - accuracy: 0.8400 - val_loss: 0.3927 - val_accuracy: 0.8149\n",
      "Epoch 3/500\n",
      "624/625 [============================>.] - ETA: 0s - loss: 0.3246 - accuracy: 0.8561\n",
      "Epoch 3: val_accuracy improved from 0.81860 to 0.82546, saving model to Question_4.h5\n",
      "625/625 [==============================] - 43s 68ms/step - loss: 0.3245 - accuracy: 0.8562 - val_loss: 0.3747 - val_accuracy: 0.8255\n",
      "Epoch 4/500\n",
      "624/625 [============================>.] - ETA: 0s - loss: 0.3132 - accuracy: 0.8573\n",
      "Epoch 4: val_accuracy improved from 0.82546 to 0.82993, saving model to Question_4.h5\n",
      "625/625 [==============================] - 33s 53ms/step - loss: 0.3131 - accuracy: 0.8573 - val_loss: 0.3725 - val_accuracy: 0.8299\n",
      "Epoch 5/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.3016 - accuracy: 0.8659\n",
      "Epoch 5: val_accuracy did not improve from 0.82993\n",
      "625/625 [==============================] - 40s 63ms/step - loss: 0.3016 - accuracy: 0.8659 - val_loss: 0.3809 - val_accuracy: 0.8258\n",
      "Epoch 6/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.2930 - accuracy: 0.8689\n",
      "Epoch 6: val_accuracy improved from 0.82993 to 0.83425, saving model to Question_4.h5\n",
      "625/625 [==============================] - 36s 58ms/step - loss: 0.2930 - accuracy: 0.8689 - val_loss: 0.3873 - val_accuracy: 0.8343\n",
      "Epoch 7/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.2839 - accuracy: 0.8756\n",
      "Epoch 7: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 36s 58ms/step - loss: 0.2839 - accuracy: 0.8756 - val_loss: 0.3792 - val_accuracy: 0.8269\n",
      "Epoch 8/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.2768 - accuracy: 0.8784\n",
      "Epoch 8: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 39s 63ms/step - loss: 0.2768 - accuracy: 0.8784 - val_loss: 0.3949 - val_accuracy: 0.8290\n",
      "Epoch 9/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.2679 - accuracy: 0.8831\n",
      "Epoch 9: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 38s 61ms/step - loss: 0.2679 - accuracy: 0.8831 - val_loss: 0.3989 - val_accuracy: 0.8244\n",
      "Epoch 10/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.2610 - accuracy: 0.8877\n",
      "Epoch 10: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 52s 83ms/step - loss: 0.2610 - accuracy: 0.8877 - val_loss: 0.4002 - val_accuracy: 0.8264\n",
      "Epoch 11/500\n",
      "624/625 [============================>.] - ETA: 0s - loss: 0.2533 - accuracy: 0.8928\n",
      "Epoch 11: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 59s 94ms/step - loss: 0.2534 - accuracy: 0.8928 - val_loss: 0.4096 - val_accuracy: 0.8250\n",
      "Epoch 12/500\n",
      "624/625 [============================>.] - ETA: 0s - loss: 0.2450 - accuracy: 0.8957\n",
      "Epoch 12: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 57s 92ms/step - loss: 0.2449 - accuracy: 0.8957 - val_loss: 0.4216 - val_accuracy: 0.8204\n",
      "Epoch 13/500\n",
      "624/625 [============================>.] - ETA: 0s - loss: 0.2377 - accuracy: 0.8982\n",
      "Epoch 13: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 54s 86ms/step - loss: 0.2376 - accuracy: 0.8984 - val_loss: 0.4219 - val_accuracy: 0.8250\n",
      "Epoch 14/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.2296 - accuracy: 0.9018\n",
      "Epoch 14: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 44s 71ms/step - loss: 0.2296 - accuracy: 0.9018 - val_loss: 0.4395 - val_accuracy: 0.8241\n",
      "Epoch 15/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.2212 - accuracy: 0.9070\n",
      "Epoch 15: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 51s 82ms/step - loss: 0.2212 - accuracy: 0.9070 - val_loss: 0.4576 - val_accuracy: 0.8246\n",
      "Epoch 16/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.2144 - accuracy: 0.9096\n",
      "Epoch 16: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 53s 84ms/step - loss: 0.2144 - accuracy: 0.9096 - val_loss: 0.4588 - val_accuracy: 0.8196\n",
      "Epoch 17/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.2062 - accuracy: 0.9134\n",
      "Epoch 17: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 46s 74ms/step - loss: 0.2062 - accuracy: 0.9134 - val_loss: 0.4903 - val_accuracy: 0.8182\n",
      "Epoch 18/500\n",
      "624/625 [============================>.] - ETA: 0s - loss: 0.1966 - accuracy: 0.9177\n",
      "Epoch 18: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 47s 75ms/step - loss: 0.1970 - accuracy: 0.9175 - val_loss: 0.5304 - val_accuracy: 0.8110\n",
      "Epoch 19/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.1913 - accuracy: 0.9212\n",
      "Epoch 19: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 52s 83ms/step - loss: 0.1913 - accuracy: 0.9212 - val_loss: 0.5053 - val_accuracy: 0.8110\n",
      "Epoch 20/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.1843 - accuracy: 0.9257\n",
      "Epoch 20: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 50s 79ms/step - loss: 0.1843 - accuracy: 0.9257 - val_loss: 0.5363 - val_accuracy: 0.8092\n",
      "Epoch 21/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.1737 - accuracy: 0.9296\n",
      "Epoch 21: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 48s 77ms/step - loss: 0.1737 - accuracy: 0.9296 - val_loss: 0.5977 - val_accuracy: 0.8120\n",
      "Epoch 22/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.1676 - accuracy: 0.9317\n",
      "Epoch 22: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 51s 81ms/step - loss: 0.1676 - accuracy: 0.9317 - val_loss: 0.5779 - val_accuracy: 0.8140\n",
      "Epoch 23/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.1598 - accuracy: 0.9359\n",
      "Epoch 23: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 51s 81ms/step - loss: 0.1598 - accuracy: 0.9359 - val_loss: 0.7185 - val_accuracy: 0.8062\n",
      "Epoch 24/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.1538 - accuracy: 0.9369\n",
      "Epoch 24: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 48s 78ms/step - loss: 0.1538 - accuracy: 0.9369 - val_loss: 0.6320 - val_accuracy: 0.8061\n",
      "Epoch 25/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.1470 - accuracy: 0.9420\n",
      "Epoch 25: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 43s 69ms/step - loss: 0.1470 - accuracy: 0.9420 - val_loss: 0.6931 - val_accuracy: 0.8052\n",
      "Epoch 26/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.1412 - accuracy: 0.9426\n",
      "Epoch 26: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 36s 58ms/step - loss: 0.1412 - accuracy: 0.9426 - val_loss: 0.7824 - val_accuracy: 0.8085\n",
      "Epoch 27/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.1333 - accuracy: 0.9466\n",
      "Epoch 27: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 33s 53ms/step - loss: 0.1333 - accuracy: 0.9466 - val_loss: 0.7477 - val_accuracy: 0.8077\n",
      "Epoch 28/500\n",
      "624/625 [============================>.] - ETA: 0s - loss: 0.1309 - accuracy: 0.9457\n",
      "Epoch 28: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 32s 51ms/step - loss: 0.1308 - accuracy: 0.9457 - val_loss: 0.8197 - val_accuracy: 0.8018\n",
      "Epoch 29/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.1249 - accuracy: 0.9493\n",
      "Epoch 29: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 42s 67ms/step - loss: 0.1249 - accuracy: 0.9493 - val_loss: 0.8731 - val_accuracy: 0.8000\n",
      "Epoch 30/500\n",
      "625/625 [==============================] - ETA: 0s - loss: 0.1188 - accuracy: 0.9517\n",
      "Reached 99.5% accuracy so cancelling training!\n",
      "\n",
      "Epoch 30: val_accuracy did not improve from 0.83425\n",
      "625/625 [==============================] - 31s 50ms/step - loss: 0.1188 - accuracy: 0.9517 - val_loss: 0.9035 - val_accuracy: 0.8050\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\samapant\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\keras\\src\\engine\\training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.\n",
      "  saving_api.save_model(\n"
     ]
    }
   ],
   "source": [
    "# Note that you'll need to save your model as a .h5 like this.\n",
    "# When you press the Submit and Test button, your saved .h5 model will\n",
    "# be sent to the testing infrastructure for scoring\n",
    "# and the score will be returned to you.\n",
    "if __name__ == '__main__':\n",
    "    model = solution_model()\n",
    "    model.save(\"Question_4.h5\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
